### ISSUE TITLE
Helper feature - Loading/creating the Lilly's CLI configuration file

### ISSUE THREAD

**Issue by xeho91** [TeamArmadilloOrg/lilly-cli#10]
**Why?**
In order to make the automation work, especially with the patterns and the fields to be filled in advance, we need to extract the information about the user. It would be very tedious to ask the very same questions every time for example when creating a new Git branch or commit message. I am talking about the questions like:
- "What's your name?",
- "What's your emoji?"

**How?**
We can make Lilly CLI ask about it only once, during the configuration process and save these data somewhere - as a configuration file.

**What?**
Create a helper(s), which will have the functionalities:
- to load this configuration file, with user's data
- to create a configuration file, if it doesn't exist _(and ask the users about his data needed for these automation tasks)_

**Dependencies:**
- [Node.js File system](https://nodejs.org/dist/latest-v12.x/docs/api/fs.html)
- [Node.js Path](https://nodejs.org/dist/latest-v12.x/docs/api/path.html)
- [Node.js Operating system - homedir](https://nodejs.org/dist/latest-v12.x/docs/api/os.html#os_os_homedir)

**Comment by xeho91** [comment]
**New problem / question:**
@lax0248917 @mariushilleke 
Since we agreed to make Lilly CLI as a side project, in a separate repository, so it could be used in more than one project... the old concept (from the older repository) requires some changes. As you might remember, it used to load the Lilly's CLI configuration file inside `./config/` directory. It was limited to just this one project, I didn't need to worry about the project's ID on Jira - previously it was just **TAWS**. What about the other projects?
I hope you see where I am going with this.

**What I propose:**
Split into two configuration files:
1. **global** one with user's data
Saved for example in the user's home directory on his device. It can be file saved as `lilly-global.config.json`.
2. **local** one with project's data
Saved in the project(s) repository(ries) `lilly-local.config.json`.
Both of these configurations should be loaded (if they exist) in advance and saved as a **Node.js global variable**, so it can be used in every module - this way we don't need to do the importing every time.
I propose to create this variable to be an object and named like this:
```js
global.LillyCLIconfiguration = {
    global: {
    // imported data from lilly-global.config.json, from the user's device home directory
     },
     local: {
     // imported data from lilly-local.config.json, from the project repository
     }
}
```

What are your thoughts? Does it make sense?
@mariushilleke I realised this is also going to block you from developing this branch command feature - the one to which you are assigned.

**Comment by mariushilleke** [comment]
In general, I d say this is awesome ane necessary if it should be used across multiple projects, it would get a 'git'-character' with local and global configuration. Am not that much into the state handling, though. Like e.g. the initial installation process for a user would be

1. Download binaries
2. Add command to path
3. Type `Lilly`
4. Initially it looks for a global configuration-file
4. a) it does not find one and asks for name and emoji
4. b) it does find one and takes those

5. In a project something like `init Lilly`
6. Lilly asks whether she should use global config or whether name and emoji should be adjusted for local config

Concerning the aforementioned point about state, does that work easily? So it actually just needs the file in the home directory wherw it just would take a look and you even could create it manually and then it would work, as well, right?

**Comment by xeho91** [comment]
>     1. Download binaries
I think it can be done when installing package (module) globally with `npm/yarn/pnpm install -g lilly-cli`
 
>     2. Add command to path
Probably won't be necessary, if the module (package - `lilly-cli`) will be installed globally. 👍 

>     3. Type `Lilly`
>     4. Initially it looks for a global configuration-file
>     5. a) it does not find one and asks for name and emoji
>     6. b) it does find one and takes those
>     7. In a project something like `init Lilly`

This is a great idea!
`lilly` has to come first, so like: `lilly init`. We can create this as a command module, to create a config locally - in the project repository.
This is an excellent idea Marius, thank you!

>     8. Lilly asks whether she should use global config or whether name and emoji should be adjusted for local config

I wouldn't put the name/emoji in the local config, because this config will be **shared** with the rest of the team. I don't think a scenario where everyone overrides these config values with their own name/emoji and pushing it would be a good idea.
I was imagining that in these local configs, we put values like, what's the project name id? Such as **TAWS**, what's the link to project board, etc.

> Concerning the aforementioned point about state, does that work easily? So it actually just needs the file in the home directory wherw it just would take a look and you even could create it manually and then it would work, as well, right?

Yeah, I can see why not! This is simpler than you think, with Node.JS File System.
We can create a "installer", when someone runs the Lilly CLI for the very first time. An example would be when in the new repository you start configuring ESLint with `eslint init`. Take a look at how it works. I would like to create something similar.

Also, I have added to the dependencies: 
[Node.js Operating system - homedir](https://nodejs.org/dist/latest-v12.x/docs/api/os.html#os_os_homedir)
This will make the task of saving/loading/editing global configuration simpler. :)

**Comment by lax0248917** [comment]
Sorry I am a little late to the party. After reviewing the pull request for this issue, it looks like the two of you hashed out how it should work, and it looks like @xeho91 was able to implement most if not all of this. I am in awe of how quickly you are at finding the perfect dependencies to make the process smoother, @xeho91. @mariushilleke You were spot on in your ideas that added some functionality to creating these config files. Sounds like a clear solution to making Lilly CLI adaptable to any project. Great job guys!
